<a href="https://colab.research.google.com/github/SandipSolunke/Artificial-Neural-Network/blob/master/LearningRules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Neural Network Learning Rules**

We know that, during ANN learning, to change the input/output behavior, we need to adjust the weights. Hence, a method is required with the help of which the weights can be modified. These methods are called Learning rules, which are simply algorithms or equations. Following are some learning rules for the neural network



In [1]:
import numpy as np

# **Hebbian Learning Rule**

This rule, one of the oldest and simplest, was introduced by Donald Hebb in his book The Organization of Behavior in 1949. It is a kind of feed-forward, unsupervised learning.



Mathematical Formula:

**Change in weight = Δw = c*o*x**

where,

c=learning constant

o=output or activation function

x=input

In [10]:
def HebbRule(x1,x2,x3,w1,n):
    w=w1

    #learning constant
    c=1

    #n no of iterations
    for i in range(n):

        for x in(x1,x2,x3):
            z=w.transpose()*x
            net=0.00
            for j in (z):
                net+=j

            #calculate output= f(net)
            o=np.sign(net)

            #delta weight=c*o*x
            deltaW=c*o*x

            #update weights
            w=deltaW+w
        print(f"Weights after {i+1} iterations :")
        print(w)
            

x1=np.array([1,-2,1.5,0])
x2=np.array([1,-0.5,-2.0,-1.5])
x3=np.array([0,1,-1,1.5])
w1=np.array([1,-1,0,0.5])
iterations=1

HebbRule(x1,x2,x3,w1,iterations)

Weights after 1 iterations :
[ 1.  -3.5  4.5  0.5]


# **Perceptron Learning Rule**

This rule is an error correcting the supervised learning algorithm of single layer feedforward networks with linear activation function, introduced by Rosenblatt.

Mathematical Formula:

**Change in weight = Δw = c*(d-o)*x**

where,

c=learning constant

d=desired output

o=output or activation function

x=input

In [9]:
def PerceptronRule(x1,x2,x3,d1,d2,d3,w1,n):
    #learning constant
    c=0.1
    w=w1

    #n no of iterations/epochs
    for i in range(n):

        for x,d in([x1,d1],[x2,d2],[x3,d3]):
            z=w.transpose()*x
            net=0
            for j in(z):
                net+=j

            #output=f(net)
            o=np.sign(net)

            #deltaW=c*(d-o)*x
            deltaW=c*(d-o)*x

            #w=deltaW+w
            w=deltaW+w
        print(f"Weights after {i+1} iterations :")
        print(w)
            

x1=np.array([1,-2,0,-1])
x2=np.array([0,1.5,-0.5,-1])
x3=np.array([-1,1,0.5,-1])
w1=np.array([1,-1,0,0.5])
d1=-1
d2=-1
d3=1
iterations=1

PerceptronRule(x1,x2,x3,d1,d2,d3,w1,iterations)

Weights after 1 iterations :
[ 0.6 -0.4  0.1  0.5]


# **Delta Learning Rule**

It is introduced by Bernard Widrow and Marcian Hoff, also called Least Mean Square LMS method, to minimize the error over all training patterns. It is kind of supervised learning algorithm with having continuous activation function.

Mathematical Formula:

**Change in weight = Δw = c*(d-o)*f'(net)**

where,

c=learning constant

d=desired output

o=output or activation function

x=input

In [8]:
def DeltaRule(x1,x2,x3,d1,d2,d3,w,n):
    #learning constant
    c=0.1

    #epochs/no of iterations
    for i in range(n):
        for x,d in ([x1,d1],[x2,d2],[x3,d3]):

            net=0    
            z=w.transpose()*x

            for j in z:
                net+=j
            
            #output=f(net)
            o=np.tanh(net)
            
            #f'(net)
            o_der=1/2*(1-o**2)
            
            #deltaw=c*(d-o)*f'(net)
            deltaW=c*(d-o)*o_der

            #new weight
            w=deltaW+w
        print(f"Weights after {i+1} iterations :")
        print(w)


x1=np.array([1,-2,0,-1])
x2=np.array([0,1.5,-0.5,-1])
x3=np.array([-1,1,0.5,-1])
d1=-1
d2=-1
d3=1
w=np.array([1,-1,0,0.5])
iterations=1

DeltaRule(x1,x2,x3,d1,d2,d3,w,iterations)

Weights after 1 iterations :
[ 9.99880101e-01 -1.00011990e+00 -1.19898579e-04  4.99880101e-01]
